class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!



  def courselist
    ["Financial Accounting",
    "Cost Analysis and Internal Controls",
    "Accounting and Financial Analysis I",
    "Taxes and Business Strategy",
    "Financial Statement Analysis",
    "Workshop in Accounting Research",
    "Economic Modeling of Accounting Issues",
    "Empirical Research in Accounting",
    "Topics in Empirical Accounting Research",
    "Empirical Research on Managers Corporate Financial Reporting Decisions",
    "Leadership Effectiveness and Development (LEAD) Lab II",
    "Kapnick Initiative Leadership Effectiveness and Development Lab",
    "Microeconomics",
    "Accelerated Microeconomics",
    "Managing the Workplace",
    "Macroeconomics",
    "Advanced Microeconomic Analysis",
    "Business in Historical Perspective",
    "Sports Analytics",
    "The Firm and the Non-Market Environment",
    "Employment Law for Entrepreneurs & Managers",
    "Money and Banking",
    "Understanding Central Banks",
    "Real Estate Investments I",
    "Real Estate Investments II",
    "Business, Politics, and Ethics",
    "International Commercial Policy",
    "International Financial Policy",
    "Managing the Firm in the Global Economy",
    "The Wealth of Nations",
    "Applied Economics Workshop",
    "Workshop in Macro and International Economics",
    "Practical Computing for Economists: Colloquium",
    "Energy Policy Practicum: Alternative Transportation Fuels",
    "Numerical Methods in Economics",
    "The Economics of Information",
    "Market Design",
    "Advanced Industrial Organization I",
    "Advanced Industrial Organization II",
    "Advanced Industrial Organization III",
    "International Macroeconomics and Trade",
    "Financial Markets in the Macroeconomy",
    "Applied Macroeconomics: Heterogeneity and Macro",
    "Entrepreneurial Finance and Private Equity",
    "New Venture Strategy",
    "Building the New Venture",
    "Special Topics in Entrepreneurship: Developing a New Venture (New Venture Challenge)",
    "Cases in Entrepreneurship Seminar",
    "Commercializing Innovation: Tools to Research and Analyze Private Enterprises",
    "Social Enterprise Lab",
    "Entrepreneurial Selling",
    "New Social Ventures",
    "Entrepreneurship through Acquisition",
    "Mergers and Acquisitions: Legal Perspectives",
    "New Venture and Small Enterprise Lab",
    "Real Estate Lab: Real Estate Challenge",
    "Entrepreneurial Discovery",
    "Energy and CleanTech Lab",
    "Private Equity Lab",
    "Venture Capital Lab",
    "Global Social Impact Practicum",
    "Investments",
    "Introductory Finance",
    "Financial Instruments",
    "Futures, Forwards, Options & Swaps: Theory and Practice",
    "History of Financial Thought and Practice",
    "Portfolio Management",
    "Behavioral Finance",
    "Hedge Fund Investing",
    "Quantimental Investment",
    "Fixed Income Asset Pricing",
    "Cases in Financial Risk Management",
    "Wealth and Family Enterprise Management",
    "Corporation Finance",
    "Cases in Financial Management",
    "Advanced Topics in Corporate Finance",
    "The Analytics of Financial Crises",
    "Behavioral and Institutional Finance",
    "Seminar:  Finance",
    "Applied Theory Workshop",
    "Theory of Financial Decisions I",
    "Theory of Financial Decisions II",
    "Theory of Financial Decisions III",
    "Topics in Empirical Finance",
    "Topics in Asset Pricing",
    "Research Projects: Finance",
    "Asset Pricing",
    "International Macroeconomics and Finance",
    "Managerial Decision Modeling",
    "Application Development",
    "Workshop in Operations/Management Science",
    "Approximate Dynamic Programming",
    "Stochastic Processes",
    "Networks I: Introduction to Modeling and Analysis",
    "Marketing Strategy",
    "Consumer Behavior",
    "Data-Driven Marketing",
    "Marketing Research",
    "New Products and Services",
    "Lab in Developing New Products and Services",
    "Pricing Strategies",
    "Going to Market: Managing Channel Strategy",
    "Digital Marketing ",
    "Digital and Algorithmic Marketing",
    "Marketing Workshop",
    "Laboratory in New Product and Strategy Development I",
    "Foundations of Advanced Quantitative Marketing",
    "Adv Mktg Theory:  Behavioral Science Approach",
    "Advanced Quantitative Marketing",
    "Marketing Literature Seminar",
    "Managing in Organizations",
    "Managerial Decision Making",
    "Power and Influence in Organizations",
    "Persuasion: Effective Business Communication",
    "Strategies and Processes of Negotiation",
    "Advanced Negotiations",
    "Ethics of Business",
    "Leading and Managing Teams",
    "Designing a Good Life",
    "Workshop in Behavioral Science",
    "Current Topics in Behavioral Science II",
    "Current Topics in Behavioral Science III",
    "Behavioral Economics",
    "Foundations of Judgment and Decision Making",
    "Strategy and Structure: Markets and Organizations",
    "Strategic Leadership",
    "Strategic Leadership in Management Networks",
    "Advanced Topics in Management Networks",
    "Technology Strategy",
    "Workshop in Organizations and Markets",
    "Operations Management: Business Process Fundamentals",
    "Supply Chain Strategy and Practice",
    "Revenue Management",
    "Managing Service Operations",
    "Project Management",
    "Healthcare Analytics ",
    "Healthcare Analytics Lab",
    "Inventory Theory and Supply Chain Management",
    "Business Statistics",
    "Applied Regression Analysis",
    "Big Data",
    "Analysis of Financial Time Series",
    "Financial Econometrics",
    "Machine Learning",
    "Statistical Insight into Marketing, Consulting, and Entrepreneurship",
    "Econometrics and Statistics Colloquium",
    "Probability and Statistics",
    "Statistical Inference",
    "Applied Econometrics",
    "Time-series Analysis for Forecasting and Model Building",
    "Applied Multivariate Analysis",
    "Bayesian Inference",
    "Competitive Strategy",
    "Business Policy",
    "The Strategy Symposium",
    "Corporate Governance",
    "Strategic Investment Decisions",
    "Game Theory",
    "Platform Competition",
    "Merger & Acquisition Strategy",
    "Innovation Strategy",
    "Reputation, Regulation and Communications – How Media Influences Business",
    "The Legal Infrastructure of Business",
    "Strategy Lab",
    "Entrepreneurship: Urban Opportunities and Solutions"]
  end

before_action :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) << :username
  devise_parameter_sanitizer.for(:sign_up) << :avatar_url

  devise_parameter_sanitizer.for(:account_update) << :avatar_url
end

end
